apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-zello
  labels:
    app: mongo-zello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-zello
  template:
    metadata:
      labels:
        app: mongo-zello
    spec:
      containers:
        - name: mongo-zello
          image: matheuslim/img-mongo-zello
          imagePullPolicy: Always
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "usr_challenge"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "123456"
            - name: MONGO_INITDB_DATABASE
              value: "admin"
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-pvc
