apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    app: mongo-zello
spec:
  selector:
    app: mongo-zello
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
  type: ClusterIP
