apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend-zello
spec:
  selector:
    app: backend-zello
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP