apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend-zello
spec:
  selector:
    app: frontend-zello
  ports:
    - name: http
      port: 80
      targetPort: 3001
  type: ClusterIP
